version: "3.8"

services:
    db:
        container_name: postgres
        build:
            context: ./database
            dockerfile: Dockerfile
            target: "database"
        ports:
            -   "5432:5432"
        volumes:
            - ./database/pg-data:/var/lib/postgresql/data
            - ./database/initdb:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: sample_db
        restart: always
volumes:
    pg-data:
